name: CD test run
description: Run CD tests

inputs:
  app:
    description: 'App to build'
    required: true

  environment:
    description: 'Environment to deploy to'
    required: true

  config_dir:
    description: 'Directory containing the config files'
    required: true

  tag:
    description: 'Tag to attach to the image'
    required: true

  gke_sa_key:
    description: 'GKE service account key'
    required: true

  gke_project:
    description: 'GKE project'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Docker
      run: gcloud --quiet auth configure-docker
      shell: bash

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gke_sa_key }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ inputs.gke_project }}

    - name: Cache kd binary
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/kd
        key: ${{ runner.os }}-kd
        restore-keys: |
          ${{ runner.os }}-kd

    - name: Set variables for tagging
      run: |
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash

    - run: |
        if ! command -v kd &> /dev/null; then
          curl -L https://github.com/voormedia/kd/releases/download/v2.0.8/linux_amd64_kd -o kd
          chmod +x kd
          sudo mv kd /usr/local/bin/
        fi

        kd build php --tag "$BRANCH-$SHA_SHORT"
